small changes

diff --git a/mastervm b/mastervm
--- a/mastervm
+++ b/mastervm
@@ -8,6 +8,17 @@ sudo apt-get install -y autoconf gcc libc6 make wget unzip apache2 php libapache
 #download and extract files
 cd /tmp
 wget -O nagioscore.tar.gz https://github.com/NagiosEnterprises/nagioscore/archive/nagios-4.3.4.tar.gz
+
+if[$? !=0]
+then
+  echo "er is iets fout gegaan, error code: " $?
+  exit
+fi
+if[$? ==0];then
+echo "het is gelukt"
+fi
+
+:'
 tar xzf nagioscore.tar.gz
 
 #compile the source
@@ -99,3 +110,4 @@ Define command{
 }
 
 #masterVM eindigt hier qua Nagios.
+'
